CREATE TABLE search_activity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     VARCHAR(255),
    search_mode VARCHAR(255),
    created_at  TIMESTAMP,
    CONSTRAINT pk_searchactivity PRIMARY KEY (id)
);
CREATE TABLE search_activity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     VARCHAR(255)                            NOT NULL,
    search_mode VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_search_activity PRIMARY KEY (id)
);

CREATE INDEX idx_search_created ON search_activity (created_at);

CREATE INDEX idx_search_user ON search_activity (user_id);