CREATE TABLE api_keys
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      VARCHAR(255),
    name         VARCHAR(255),
    key_hash     VARCHAR(255),
    key_prefix   VARCHAR(255),
    status       VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    last_used_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_api_keys PRIMARY KEY (id)
);